In [1]:
import numpy as np

def calculate_inertia_parrallel_axis(m,r,I):
    I_res = np.empty_like(I)
    r_aux = -r
    I_res[0,0] = I[0,0] + (np.square(r_aux[1]) + np.square(r_aux[2]))*m
    I_res[1,1] = I[1,1] + (np.square(r_aux[0]) + np.square(r_aux[2]))*m
    I_res[2,2] = I[2,2] + (np.square(r_aux[0]) + np.square(r_aux[1]))*m
    I_res[0,1] = I[0,1] - r_aux[0] * r_aux[1] * m
    I_res[0,2] = I[0,2] - r_aux[0] * r_aux[2] * m
    I_res[1,2] = I[1,2] - r_aux[1] * r_aux[1] * m
    I_res[1,0] = I_res[0,1]
    I_res[2,0] = I_res[0,2]
    I_res[2,1] = I_res[1,2]
    return I_res

In [2]:
I = np.matrix('0.004212 0 0 ; 0 0.004212 0; 0 0 0.004212')
com = np.array([0 , 0 , -0.09])
m = 1.3
I_sensor_frame = calculate_inertia_parrallel_axis(m, com, I)
I_link = np.matrix('0.05 0 0 ; 0 0.05 0; 0 0 0.05')
com_link = np.array([0 , 0 , -0.08])
m_link = 0.5
I_link_sensor_frame = calculate_inertia_parrallel_axis(m_link, com_link, I_link)
print('Inertia tensor object in sensor frame: \n {}'.format(I_sensor_frame))
print('Inertia tensor link in sensor frame: \n {}'.format(I_link_sensor_frame))
I_ges = I_sensor_frame + I_link_sensor_frame
print('Inertia tensor sum in sensor frame: \n {}'.format(I_ges))

Inertia tensor object in sensor frame: 
 [[0.014742 0.       0.      ]
 [0.       0.014742 0.      ]
 [0.       0.       0.004212]]
Inertia tensor link in sensor frame: 
 [[0.0532 0.     0.    ]
 [0.     0.0532 0.    ]
 [0.     0.     0.05  ]]
Inertia tensor sum in sensor frame: 
 [[0.067942 0.       0.      ]
 [0.       0.067942 0.      ]
 [0.       0.       0.054212]]


In [6]:
I = np.matrix('0.002212 0 0 ; 0 0.001212 0; 0 0 0.003212')
com = np.array([0.02 ,0.03, 0.05])
m = 1.33
I_sensor_frame = calculate_inertia_parrallel_axis(m, com, I)
print('Inertia tensor object in sensor frame: \n {}'.format(I_sensor_frame))        
        
        

Inertia tensor object in sensor frame: 
 [[ 0.006734 -0.000798 -0.00133 ]
 [-0.000798  0.005069 -0.001197]
 [-0.00133  -0.001197  0.004941]]
