In [4]:
import numpy as np

def calculate_inertia_parrallel_axis(m,r,I):
    I_res = np.empty_like(I)
    r_aux = -r
    I_res[0,0] = I[0,0] + (np.square(r_aux[1]) + np.square(r_aux[2]))*m
    I_res[1,1] = I[1,1] + (np.square(r_aux[0]) + np.square(r_aux[2]))*m
    I_res[2,2] = I[2,2] + (np.square(r_aux[0]) + np.square(r_aux[1]))*m
    I_res[0,1] = I[0,1] - r_aux[0] * r_aux[1] * m
    I_res[0,2] = I[0,2] - r_aux[0] * r_aux[2] * m
    I_res[1,2] = I[1,2] - r_aux[1] * r_aux[1] * m
    I_res[1,0] = I_res[0,1]
    I_res[2,0] = I_res[0,2]
    I_res[2,1] = I_res[1,2]
    return I_res

In [3]:


I = np.matrix('0.004212 0 0 ; 0 0.004212 0; 0 0 0.004212')
com = np.array([-0.03 , -0.03 , -0.09])
m = 1.31
I_sensor_frame = calculate_inertia_parrallel_axis(m, com, I)
I_link = np.matrix('0.05 0 0 ; 0 0.05 0; 0 0 0.05')
com_link = np.array([0 , 0 , -0.08])
m_link = 0.5
I_link_sensor_frame = calculate_inertia_parrallel_axis(m_link, com_link, I_link)
print('Inertia tensor object in sensor frame: \n {}'.format(I_sensor_frame))
print('Inertia tensor link in sensor frame: \n {}'.format(I_link_sensor_frame))
I_ges = I_sensor_frame + I_link_sensor_frame
print('Inertia tensor sum in sensor frame: \n {}'.format(I_ges))

Inertia tensor object in sensor frame: 
 [[ 0.016002 -0.001179 -0.003537]
 [-0.001179  0.016002 -0.001179]
 [-0.003537 -0.001179  0.00657 ]]
Inertia tensor link in sensor frame: 
 [[0.0532 0.     0.    ]
 [0.     0.0532 0.    ]
 [0.     0.     0.05  ]]
Inertia tensor sum in sensor frame: 
 [[ 0.069202 -0.001179 -0.003537]
 [-0.001179  0.069202 -0.001179]
 [-0.003537 -0.001179  0.05657 ]]


In [6]:
I = np.matrix('0.004 0 0 ; 0 0.004 0; 0 0 0.004')
com = np.array([-0.00241322 , 0.000670019 , -0.0899771])
m = 1.29794
I_sensor_frame = calculate_inertia_parrallel_axis(m, com, I)
print('Inertia tensor object in sensor frame: \n {}'.format(I_sensor_frame))


Inertia tensor object in sensor frame: 
 [[ 1.45085473e-02  2.09864341e-06 -2.81827601e-04]
 [ 2.09864341e-06  1.45155233e-02 -5.82678312e-07]
 [-2.81827601e-04 -5.82678312e-07  4.00814140e-03]]


In [ ]:
1.31003
estimated center of mass: 
 0.029832 0.0298581 0.0898779
estimated Inertia: 
  0.0159203 -0.00107207 -0.00354551
-0.00107207   0.0158867 -0.00353258
-0.00354551 -0.00353258   0.0065347

In [18]:
from numpy import linalg as LA
def isRotationMatrix(M):
    tag = False
    I = np.identity(M.shape[0])
    if np.all((np.matmul(M, M.T)) == I) and (np.linalg.det(M)==1): tag = True
    return tag  
def normalizezRot(R):
    R_normalized= np.zeros(R.shape)
    for i in np.arange(3):
        for j in np.arange(3):
            R_axis = R[:,i]
            R_axis_norm = LA.norm(R_axis);
            R_normalized[j,i] = R[j,i]/ R_axis_norm
    print(R_normalized)        
    return R_normalized
#         R(0,0)
    

In [26]:
ori = np.matrix([[0.07 ,  -0.84 ,  -0.],[0 ,  0.2,   -0.9],[0.93,   0.2  ,0.316227766]])

              

In [27]:
isRotationMatrix(ori)

False

In [23]:
isRotationMatrix(normalizezRot(ori))

[[ 0.36965564 -0.84025211 -0.        ]
 [-0.00799255  0.43012906 -0.98639392]
 [ 0.92913445  0.33009904  0.16439899]]


False