In [2]:
import numpy as np

def calculate_inertia_parrallel_axis(m,r,I):
    I_res = np.empty_like(I)
    r_aux = -r
    I_res[0,0] = I[0,0] + (np.square(r_aux[1]) + np.square(r_aux[2]))*m
    I_res[1,1] = I[1,1] + (np.square(r_aux[0]) + np.square(r_aux[2]))*m
    I_res[2,2] = I[2,2] + (np.square(r_aux[0]) + np.square(r_aux[1]))*m
    I_res[0,1] = I[0,1] - r_aux[0] * r_aux[1] * m
    I_res[0,2] = I[0,2] - r_aux[0] * r_aux[2] * m
    I_res[1,2] = I[1,2] - r_aux[1] * r_aux[1] * m
    I_res[1,0] = I_res[0,1]
    I_res[2,0] = I_res[0,2]
    I_res[2,1] = I_res[1,2]
    return I_res

In [4]:
I = np.matrix('0.004212 0 0 ; 0 0.004212 0; 0 0 0.004212')
com = np.array([0 , 0 , -0.09])
m = 1.3
I_sensor_frame = calculate_inertia_parrallel_axis(m, com, I)
I_link = np.matrix('0.05 0 0 ; 0 0.05 0; 0 0 0.05')
com_link = np.array([0 , 0 , -0.08])
m_link = 0.5
I_link_sensor_frame = calculate_inertia_parrallel_axis(m_link, com_link, I_link)
print('Inertia tensor object in sensor frame: \n {}'.format(I_sensor_frame))
print('Inertia tensor link in sensor frame: \n {}'.format(I_link_sensor_frame))
I_ges = I_sensor_frame + I_link_sensor_frame
print('Inertia tensor sum in sensor frame: \n {}'.format(I_ges))

Inertia tensor in sensor frame: 
 [[0.015912 0.       0.      ]
 [0.       0.015912 0.      ]
 [0.       0.       0.004212]]
[[0.0532 0.     0.    ]
 [0.     0.0532 0.    ]
 [0.     0.     0.05  ]]
[[0.069112 0.       0.      ]
 [0.       0.069112 0.      ]
 [0.       0.       0.054212]]


In [6]:
I = np.matrix('0.004 0 0 ; 0 0.004 0; 0 0 0.004')
com = np.array([-0.00241322 , 0.000670019 , -0.0899771])
m = 1.29794
I_sensor_frame = calculate_inertia_parrallel_axis(m, com, I)
print('Inertia tensor object in sensor frame: \n {}'.format(I_sensor_frame))


Inertia tensor object in sensor frame: 
 [[ 1.45085473e-02  2.09864341e-06 -2.81827601e-04]
 [ 2.09864341e-06  1.45155233e-02 -5.82678312e-07]
 [-2.81827601e-04 -5.82678312e-07  4.00814140e-03]]
